import type { Metadata } from "next";
import Link from "next/link";
import { legal } from "@/lib/legal";

export const metadata: Metadata = { title: "Terms of Service — Ghost PM" };

export default function TermsPage() {
  const { company, contact, jurisdiction, updated } = legal;
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground">Last updated {updated}</p>

      <p>
        These terms govern your use of Ghost PM (the &quot;Service&quot;), operated by {company} (&quot;we&quot;,
        &quot;us&quot;). By creating an account or using the Service you agree to them. If you use the Service on behalf
        of an organization, you agree on its behalf.
      </p>

      <h2>1. Accounts</h2>
      <p>
        You sign in with GitHub and must keep your GitHub account secure. You&apos;re responsible for activity in your
        account and in workspaces you own. You must be at least 16 years old.
      </p>

      <h2>2. Your content</h2>
      <p>
        You keep all rights to what you put into the Service — notes, voice transcripts, screenshots, tasks, comments
        (&quot;Content&quot;). You grant us a limited license to host, process and display Content only to provide the
        Service, including sending it to our AI provider to generate tasks, prompts and plans. We don&apos;t use your
        Content to train AI models. Don&apos;t submit secrets (API keys, passwords) or data you don&apos;t have the right
        to share.
      </p>

      <h2>3. AI output</h2>
      <p>
        Tasks, priorities, agent prompts and roadmaps are generated by AI and can be wrong or incomplete. Review them
        before acting — especially before running generated prompts in coding agents with access to your code.
      </p>

      <h2>4. GitHub access</h2>
      <p>
        We request the <code>repo</code> scope so we can list your repositories and create or read issues when you ask
        us to. We only act on repositories in response to your actions (e.g. &quot;Push to GitHub&quot;, &quot;Sync
        GitHub&quot;). You can revoke access anytime in your GitHub settings.
      </p>

      <h2>5. Plans, billing and cancellation</h2>
      <p>
        The Free plan includes a monthly allowance of AI-created tasks per workspace. Pro is billed monthly per seat
        (workspace member) through our reseller and merchant of record, Lemon Squeezy, whose terms also apply to your
        purchase. Seat count follows your member count and changes are prorated. You can cancel anytime from Billing;
        Pro stays active until the end of the paid period. Except where required by law, fees are non-refundable.
        We may change prices with at least 30 days&apos; notice.
      </p>

      <h2>6. Acceptable use</h2>
      <ul>
        <li>No illegal content, malware, or content that infringes others&apos; rights.</li>
        <li>No attempts to break, overload, scrape or reverse-engineer the Service, or to bypass usage limits.</li>
        <li>No using the Service to build a competing product from its outputs at scale.</li>
      </ul>
      <p>We may suspend accounts that violate these terms or put the Service or other users at risk.</p>

      <h2>7. Availability and changes</h2>
      <p>
        We work hard to keep the Service running but don&apos;t guarantee uninterrupted availability. We may change or
        discontinue features; for paid features we&apos;ll give reasonable notice.
      </p>

      <h2>8. Disclaimer and limitation of liability</h2>
      <p>
        The Service is provided &quot;as is&quot;. To the extent permitted by law, we disclaim all implied warranties and
        are not liable for indirect or consequential damages, lost profits or data. Our total liability is limited to
        the amount you paid us in the 12 months before the claim.
      </p>

      <h2>9. Termination</h2>
      <p>
        You can delete your account anytime in Settings → Account. We delete your data as described in our{" "}
        <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>10. Governing law</h2>
      <p>These terms are governed by the laws of {jurisdiction}.</p>

      <h2>11. Contact</h2>
      <p>
        Questions? <a href={`mailto:${contact}`}>{contact}</a>
      </p>
    </>
  );
}
